org: joshsdoman
app: am-i-legitimate
service: SecondDegree
frameworkVersion: '2 || 3'
useDotenv: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  environment:
    BEARER_TOKEN: ${env:BEARER_TOKEN}

functions:
  follows-my-followers-test:
    handler: handler.followsMyFollowersTest
    events:
      - http:
          path: /test
          method: get
    package:
      patterns:
        - functions
  follows-my-followers:
    handler: handler.followsMyFollowers
    events:
      - http:
          path: /
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    package:
      patterns:
        - functions
